CREATE DATABASE mydb2;
USE mydb2;

CREATE TABLE Board (
	id INT PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(100) NOT NULL DEFAULT '제목 없음',
	body VARCHAR(5000) NOT NULL DEFAULT '내용 없음',
    inserted DATETIME NOT NULL DEFAULT NOW()
);

DESC Board;

SELECT * FROM Board;

SET SQL_SAFE_UPDATES = 1;
UPDATE Board 
SET inserted = DATE_SUB(inserted, INTERVAL 1 DAY);